# Generated by Django 2.1.7 on 2019-02-28 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='reg_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'added'), ('r', 'registration'), ('s', 'started'), ('p', 'paused'), ('e', 'ended')], default='a', help_text='status of Contest', max_length=1),
        ),
        migrations.AddField(
            model_name='contest',
            name='text',
            field=models.TextField(default='', max_length=1000, verbose_name='description of contest'),
        ),
    ]
