# Generated by Django 2.1.7 on 2019-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20190304_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleaderboard',
            name='lb_score',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='last score of user on contest', max_digits=10),
        ),
    ]
