# Generated by Django 2.1.7 on 2019-03-07 02:03

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20190307_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='filepath',
            field=models.FileField(default='', upload_to='submit_files/', validators=[challenge.models.validate_file_size], verbose_name=''),
        ),
    ]
