# Generated by Django 2.1.7 on 2019-03-12 14:15

import challenge.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20190312_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='filepath',
            field=models.FileField(default='', upload_to=challenge.models.content_file_name, validators=[challenge.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name=''),
        ),
    ]
